### ISSUE TITLE
what does this meaning, thanks

### ISSUE THREAD

**Issue by liamxg** [clifmckee/bat_CoV_review#3]
"%ni%" <- Negate("%in%")

**Comment by clifmckee** [comment]
It sets up a function that can be very useful for filtering. Just like the `%in%` function, you can filter a list or a data frame to just the values you set in your search (for example, `df[df$column1 %in% c(1, 2, 3),]`. The `%ni%` function I set up here basically does the opposite of `%in%`, it can be used to filter a list or data frame to **all the other** values that are **not** included in the search terms. I used this functions in older versions of this analysis, but not anymore. I just never removed this line.

**Comment by liamxg** [comment]
thanks, you are very nice, I am appreciated for this.

**Comment by liamxg** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/46078579/159152208-e70df89f-0a75-4d8f-b3c7-37d87461cb5d.png">
this is also using "%ni%".
